services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: unmtransinfo/drugcen-db:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    image: unmtransinfo/drugcen-web:latest
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - "8000"
    volumes:
      - .:/app
      - static_volume:/app/static
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    image: unmtransinfo/drugcen-nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
    depends_on:
      - web
    restart: unless-stopped

volumes:
  pgdata:
  static_volume:
